### ISSUE TITLE
Modules tomllib or tomli not found when importing cmeel

### ISSUE THREAD

**Issue by stephane-caron** [cmake-wheel/cmeel#88]
The CI for [Upkie](https://github.com/upkie/upkie) started failing tonight after an innocuous change to the readme. (The same pipeline run successfully last week.)

The error points to `tomllib` and `tomli` in `cmeel`:

```
2023-12-11T19:10:00.4145884Z Error processing line 1 of /home/runner/.local/lib/python3.10/site-packages/cmeel.pth:
2023-12-11T19:10:00.4146731Z 
2023-12-11T19:10:00.4147174Z   Traceback (most recent call last):
2023-12-11T19:10:00.4148444Z     File "/home/runner/.local/lib/python3.10/site-packages/cmeel/impl.py", line 11, in <module>
2023-12-11T19:10:00.4267540Z       import tomllib  # type: ignore
2023-12-11T19:10:00.4268820Z   ModuleNotFoundError: No module named 'tomllib'
2023-12-11T19:10:00.4269525Z   
2023-12-11T19:10:00.4270266Z   During handling of the above exception, another exception occurred:
2023-12-11T19:10:00.4271376Z   
2023-12-11T19:10:00.4589626Z   Traceback (most recent call last):
2023-12-11T19:10:00.4590583Z     File "/usr/lib/python3.10/site.py", line 192, in addpackage
2023-12-11T19:10:00.4591471Z       exec(line)
2023-12-11T19:10:00.4592259Z     File "<string>", line 1, in <module>
2023-12-11T19:10:00.4593791Z     File "/home/runner/.local/lib/python3.10/site-packages/cmeel/__init__.py", line 4, in <module>
2023-12-11T19:10:00.4595809Z       from .build import build_editable, build_sdist, build_wheel
2023-12-11T19:10:00.4597325Z     File "/home/runner/.local/lib/python3.10/site-packages/cmeel/build.py", line 6, in <module>
2023-12-11T19:10:00.4598499Z       from .impl import build_impl
2023-12-11T19:10:00.4599897Z     File "/home/runner/.local/lib/python3.10/site-packages/cmeel/impl.py", line 13, in <module>
2023-12-11T19:10:00.4601085Z       import tomli as tomllib  # type: ignore
2023-12-11T19:10:00.4602036Z   ModuleNotFoundError: No module named 'tomli'
2023-12-11T19:10:00.4602574Z 
2023-12-11T19:10:00.4603018Z Remainder of file ignored
```

It is all the more strange that `tomli` seems installed:

```
2023-12-11T19:06:09.1450842Z Requirement already satisfied: tomli<3.0.0,>=2.0.1 in /usr/local/lib/python3.10/dist-packages (from cmeel->pin) (2.0.1)
```

Do you have an idea as to what is going on here?

## Further details

Some cmeel versions:

```
2023-12-11T19:06:08.1942484Z Collecting cmeel (from pin)
2023-12-11T19:06:08.2020974Z   Downloading cmeel-0.53.0-py3-none-any.whl.metadata (5.1 kB)
2023-12-11T19:06:08.2391169Z Collecting cmeel-boost~=1.83.0 (from pin)
2023-12-11T19:06:08.2474676Z   Downloading cmeel_boost-1.83.0-0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (1000 bytes)
2023-12-11T19:06:08.2765840Z Collecting cmeel-console-bridge<2,>=1.0.2.2 (from pin)
2023-12-11T19:06:08.2840593Z   Downloading cmeel_console_bridge-1.0.2.2-3-py3-none-manylinux_2_28_x86_64.whl.metadata (970 bytes)
2023-12-11T19:06:08.3126796Z Collecting cmeel-tinyxml<3,>=2.6.2.2 (from pin)
2023-12-11T19:06:08.3207152Z   Downloading cmeel_tinyxml-2.6.2.3-0-py3-none-manylinux_2_28_x86_64.whl.metadata (389 bytes)
2023-12-11T19:06:08.3509842Z Collecting cmeel-urdfdom<4,>=3.1.0.3 (from pin)
2023-12-11T19:06:08.3593375Z   Downloading cmeel_urdfdom-3.1.1.1-0-py3-none-manylinux_2_28_x86_64.whl.metadata (2.8 kB)
```

**Comment by nim65s** [comment]
Thanks, this is a quite hard issue :)
I'll try something.

**Comment by nim65s** [comment]
It failed, and I'm too tired for tonight. You can workaround your current issue with a `python -m pip install --force-reinstall tomli`, and I'll provide a cleaner fix later :)

**Comment by nim65s** [comment]
@stephane-caron : this should be good now, we had to wait for v0.53.2. Could you try again https://github.com/upkie/upkie/actions/runs/7181977028/job/19557475293 ?

It's working on my side: https://github.com/nim65s/upkie/actions/runs/7182356812/job/19558681741

**Comment by stephane-caron** [comment]
Thank you for keeping track :smiley: (Next times I'll wait at least 3-4 hours before taking action!)

I've re-run the job and it passes now :+1:
